<?php

/*
   ----------------------------------------------------------------------
   Monitoring plugin for GLPI
   Copyright (C) 2010-2011 by the GLPI plugin monitoring Team.

   https://forge.indepnet.net/projects/monitoring/
   ----------------------------------------------------------------------

   LICENSE

   This file is part of Monitoring plugin for GLPI.

   Monitoring plugin for GLPI is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 2 of the License, or
   any later version.

   Monitoring plugin for GLPI is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Monitoring plugin for GLPI.  If not, see <http://www.gnu.org/licenses/>.

   ------------------------------------------------------------------------
   Original Author of file: David DURIEUX
   Co-authors of file:
   Purpose of file:
   ----------------------------------------------------------------------
 */

if (!defined('GLPI_ROOT')) {
   die("Sorry. You can't access directly to this file");
}

class PluginMonitoringShinken extends CommonDBTM {
   

   function generateConfig() {
      global $DB,$CFG_GLPI,$LANG;

      


      return true;
   }


   function generateCommandsCfg() {
      $config = "# Generated by plugin monitoring for GLPI\n# on ".date("Y-m-d H:i:s")."\n\n";

      $pluginMonitoringCommand = new PluginMonitoringCommand();

      $a_list = $pluginMonitoringCommand->find();
      foreach ($a_list as $data) {
         $config .= "# ".$data['name']."\n";
         $config .= "define command {\n";
         $config .= "       command_name     ".$data['command_name']."\n";
         $config .= "       command_line     ".$data['command_line']."\n";
         $config .= "}\n";
         $config .= "\n\n";
      }
      return array('commands.cfg', $config);
   }


   
   function generatehostsCfg() {
      $config = "# Generated by plugin monitoring for GLPI\n# on ".date("Y-m-d H:i:s")."\n\n";

      $pluginMonitoringHost = new PluginMonitoringHost();
      $pluginMonitoringHost_Host = new PluginMonitoringHost_Host();
      $pluginMonitoringCommand = new PluginMonitoringCommand();
      $pluginMonitoringCheck = new PluginMonitoringCheck();
      $networkPort = new NetworkPort();

      $a_list = $pluginMonitoringHost->find();
      foreach ($a_list as $data) {
         $classname = $data['itemtype'];
         $class = new $classname;
         $class->getFromDB($data['items_id']);

         $config .= "define host {\n";
         $config .= "       host_name     ".$class->getTypeName()."-".$class->fields['name']."\n";
            $ip = $class->fields['name'];
            if ($data['itemtype'] == 'NetworkEquipment') {
               if ($class->fields['ip'] != '') {
                  $ip = $class->fields['ip'];
               }
            } else {
               $a_listnetwork = $networkPort->find("`itemtype`='".$data['itemtype']."'
                  AND `items_id`='".$data['items_id']."'");
               foreach ($a_listnetwork as $datanetwork) {
                  if ($datanetwork['ip'] != '' AND $datanetwork['ip'] != '127.0.0.1') {
                     $ip = $datanetwork['ip'];
                     break;
                  }
               }
            }
         $config .= "       address     ".$ip."\n";
            $a_parents = array();
            $a_list_parent = $pluginMonitoringHost_Host->find("`plugin_monitoring_hosts_id_1`='".$data['id']."'");
            foreach ($a_list_parent as $data_parent) {
               $pluginMonitoringHost->getFromDB($data_parent['plugin_monitoring_hosts_id_2']);
               $classnameparent = $pluginMonitoringHost->fields['itemtype'];
               $classparent = new $classnameparent;
               $classparent->getFromDB($pluginMonitoringHost->fields['items_id']);
               $a_parents[] = $classparent->getTypeName()."-".$classparent->fields['name'];
            }
         $config .= "       parents     ".  implode(',', $a_parents)."\n";
         $pluginMonitoringCommand->getFromDB($data['plugin_monitoring_commands_id']);
         $config .= "       check_command     ".$pluginMonitoringCommand->fields['name']."\n";
         $pluginMonitoringCheck->getFromDB($data['plugin_monitoring_checks_id']);
         $config .= "       check_interval     ".$pluginMonitoringCheck->fields['check_interval']."\n";
         $config .= "       retry_interval     ".$pluginMonitoringCheck->fields['retry_interval']."\n";
         $config .= "       max_check_attempts  ".$pluginMonitoringCheck->fields['max_check_attempts']."\n";

         $config .= "}\n";
         $config .= "\n\n";
      }
      return array('hosts.cfg', $config);
   }

}

?>